version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Starting the Customer API build...
  build:
    commands:
      - echo Build and test started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`. Starting packaging
      - mvn package
artifacts:
  files:
    - target/customer-0.0.2-SNAPSHOT.jar
